spring.application.name=literarytravelers-books


server.port=8081


# Configurações de DataSource usadas pelo JPA e Flyway
spring.datasource.url=jdbc:postgresql://localhost:5432/literarytravelers_books
spring.datasource.username=postgres
spring.datasource.password=311708
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.url=jdbc:postgresql://localhost:5432/literarytravelers_books
spring.flyway.user=postgres
spring.flyway.password=311708


# Configurações JPA
# Desative o gerenciamento automático do Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Configurações Flyway
spring.flyway.enabled=true                      
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# mvn flyway:clean -Dflyway.cleanDisabled=false

logging.level.org.springframework.jdbc.datasource.DriverManagerDataSource=DEBUG

